version: 0.2
phases:
  install:
    commands:
      - echo "Nothing to do"

  pre_build:
    commands:
      - echo "Nothing to do"
      - touch hello.txt

  build:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --s3-prefix $SERVICE --output-template-file app-output_sam.yaml

  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - app-output_sam.yaml
  discard-paths: yes
